/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./App.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        surface: '#ffffff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#fafafa',
        'surface-container-high': '#f3f3f3',
        'surface-container-highest': '#ebebeb',
        primary: '#111316',
        'primary-container': '#ffcc00',
        'on-primary-fixed': '#1c1600',
        'on-surface': '#1a1c1c',
        'on-surface-variant': '#5c5f5f',
        secondary: '#2260a2',
        'tertiary-container': '#00e7fe',
        success: '#1b8354',
        warning: '#c56d00',
        error: '#ba1a1a',
        outline: 'rgba(26, 28, 28, 0.35)',
        'outline-variant': 'rgba(26, 28, 28, 0.2)',
        'cta-primary-bg': '#ffcc00',
        'cta-primary-text': '#111316',
        'cta-secondary-bg': '#111316',
        'cta-secondary-text': '#ffffff',
        'focus-ghost': 'rgba(26, 28, 28, 0.2)',
        'glass-surface': 'rgba(255, 255, 255, 0.78)',
        'surface-nested-1': '#f3f3f3',
        'surface-nested-2': '#ffffff',
        'status-success-bg': '#e8f8f0',
        'status-warning-bg': '#fff4e5',
        'status-error-bg': '#fdeeee',
      },
      spacing: {
        xxs: '2px',
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        xxl: '48px',
        xxxl: '64px',
      },
      borderRadius: {
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
      },
      fontFamily: {
        display: ['PlusJakartaSans_500Medium'],
        headline: ['PlusJakartaSans_500Medium'],
        title: ['PlusJakartaSans_500Medium'],
        body: ['PlusJakartaSans_500Medium'],
        label: ['PlusJakartaSans_500Medium'],
        caption: ['PlusJakartaSans_500Medium'],
      }
    },
  },
  plugins: [],
}
